services:
  - type: web
    name: movie-ticket-system
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      # This tells Render to read your GOOGLE_CREDENTIALS
      # from the 'Environment' tab in the dashboard.
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_PASSWORD
        sync: false